DatingAppProject/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
import notifications.urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path(
        "inbox/notifications/", include(notifications.urls, namespace="notifications")
    ),
    path("", include("user_profile.urls")),
    path("filter/", include("find_users.urls")),
    path("chat/", include("chat.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path
from chat.views import (
    ChatBoxView,
    get_private_chat,
    get_shared_key,
    delete_chat_thread,
    block_user,
)

urlpatterns = [
    path("", ChatBoxView, name="chatbox"),
    path("get_messages/", get_private_chat, name="get_private_chat"),
    path("get_shared_key/", get_shared_key, name="get_shared_key"),
    path("delete_chat/", delete_chat_thread, name="delete-chat"),
    path("block_user/", block_user),
]

user_profile/models.py
from datetime import date
import os
from pyexpat import model
import uuid

import math
from django.db.models.expressions import RawSQL
from django.db.backends.signals import connection_created
from django.dispatch import receiver

from bisect import bisect
from django.conf import settings
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from common.constants import (
    HEIGHT,
    LOOKING_FOR_CHOICES,
    GENDER_CHOICES,
    signs,
    ZODIAC_CHOICES,
    HAIR_COLOUR,
    HAIR_LENGTH,
    BODY_TYPE,
    RELIGION,
    RELATIONSHIP_STATUS,
    EDUCATION,
    EYE_COLOR,
    HEIGHT,
)
from common.models import CommonInfo


User = settings.AUTH_USER_MODEL


def validate_age(value):
    if value and (timezone.now().date() - value).days < 365.25 * 18:
        raise ValidationError("User must be 18 years or older.")


def validate_phone_number(value):
    if not value.isdigit() or len(value) != 10:
        raise ValidationError(
            _("Phone number must contain exactly 10 digits."),
            code="invalid_phone_number",
        )


# Renames user uploaded images
def path_and_rename(instance, filename):
    upload_to = "media/profile_images"
    ext = filename.split(".")[-1]

    if instance.pk:
        filename = "{}.{}".format(instance.pk, ext)
    else:
        filename = "{}.{}".format(uuid.uuid4().hex, ext)
    return os.path.join(upload_to, filename)


# Profile model for user-- contains personal information
class UserProfile(CommonInfo):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="profile")
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    bio = models.TextField(max_length=100, default="", blank=False)
    date_of_birth = models.DateField(null=True, validators=[validate_age])
    address = models.CharField(max_length=100, null=True)
    phone = models.CharField(
        max_length=10, null=True, validators=[validate_phone_number]
    )

    gender = models.CharField(choices=GENDER_CHOICES, max_length=6, default="MALE")

    profile_picture = models.ImageField(upload_to=path_and_rename, null=True)

    lat = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    long = models.DecimalField(max_digits=9, decimal_places=6, null=True)
    age = models.IntegerField(null=True, blank=True)
    zodiac = models.CharField(
        choices=ZODIAC_CHOICES, max_length=15, null=True, blank=True
    )

    def save(self, *args, **kwargs):
        if self.date_of_birth is not None:
            self.age = self.get_age()
            self.zodiac = self.get_zodiac()
        super(UserProfile, self).save(*args, **kwargs)

    def get_age(self):
        return int((date.today() - self.date_of_birth).days / 365.25)

    def get_zodiac(self):
        month = int(self.date_of_birth.strftime("%m"))
        day = int(self.date_of_birth.strftime("%d"))
        return signs[bisect(signs, (month, day))][2]

    def __str__(self):
        return self.user.email


class UserDescription(CommonInfo):
    user = models.OneToOneField(
        UserProfile, on_delete=models.CASCADE, related_name="description"
    )
    height = models.CharField(choices=HEIGHT, default="4 to 5", max_length=10)
    eye_color = models.CharField(choices=EYE_COLOR, max_length=10, default="BLACK")
    hair_length = models.CharField(
        choices=HAIR_LENGTH, default="LONG", blank=False, max_length=100
    )
    hair_colour = models.CharField(
        choices=HAIR_COLOUR, default="BLACK", blank=False, max_length=10
    )
    body_type = models.CharField(
        choices=BODY_TYPE, default="AVERAGE", blank=False, max_length=15
    )
    religion = models.CharField(
        choices=RELIGION, default="HINDU", blank=False, max_length=100
    )
    relationship_status = models.CharField(
        choices=RELATIONSHIP_STATUS, default="SINGLE", blank=False, max_length=100
    )
    education = models.CharField(
        choices=EDUCATION, default="HIGH SCHOOL", blank=False, max_length=100
    )
    looking_for = models.CharField(
        choices=LOOKING_FOR_CHOICES, max_length=6, default="BOTH"
    )
    is_completed = models.BooleanField(default=False)


class UserInterest(CommonInfo):
    user = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, related_name="interest"
    )
    title = models.CharField(max_length=20, blank=True, null=True)


class UserConnection(CommonInfo):
    owner = models.OneToOneField(
        UserProfile, on_delete=models.CASCADE, related_name="connection"
    )
    connections = models.ManyToManyField(UserProfile)

    def __str__(self):
        return self.owner.user.email


class BlockedUser(CommonInfo):
    owner = models.OneToOneField(
        UserProfile, on_delete=models.CASCADE, related_name="blocked_users"
    )
    users = models.ManyToManyField(UserProfile)

    def __str__(self):
        return self.owner.user.email


class HeartQuerySet(models.QuerySet):
    def get_mutual_hearts(self, user_1, user_2):
        qs = Heart.objects.filter(
            Q(sent_by=user_1, received_by=user_2)
            | Q(sent_by=user_2, received_by=user_1)
        )
        return qs


class Heart(CommonInfo):
    sent_by = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, related_name="heart_sender"
    )
    received_by = models.ForeignKey(
        UserProfile, on_delete=models.CASCADE, related_name="heart_receiver"
    )

    objects = HeartQuerySet.as_manager()


class Key(models.Model):
    keys_owner = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name="keys"
    )
    private_key = models.TextField(blank=True, null=True)
    public_key = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.keys_owner.email

templates/profile/base_notifications.html
{% extends 'base.html' %}
{% load static %}
{% load notifications_tags %}

{% block css %}
<link rel="stylesheet" href="{% static 'css/notifications.css' %}">

{% endblock %}
{{unread_count|pluralize:"es"}}
{% block content %}

<section class="section-50">
    <div class="container">
        <h3 class="m-b-50 heading-line"><span id="nCount">{% live_notify_badge %}</span> New Matches <i class="fa fa-bell text-muted"></i></h3>
        <div class="notification-ui_dd-content">
            {% for notification in notifications %}
                <div class="notification-list {% if notification.unread %} notification-list--unread {% endif %}"  data-slug="{{notification.slug}}" data-user="{{notification.actor.profile.id}}" onclick="markAsRead()">
                        <div class="notification-list_content">
                            <div class="notification-list_img">
                                <img src="{{notification.actor.profile.profile_picture.url}}" alt="user">
                            </div>
                            <div class="notification-list_detail">
                                <p class="text-dark"><b>{{notification.actor.profile.first_name}}</b> sent you a heart.</p>
                                <p class="text-muted">Send back a heart to start chatting now.</p>
                                <p class="text-muted"><small>{{notification.timestamp|timesince}} ago</small></p>
                            </div>
                        </div>
                        <div class="notification-list_feature-img">
                            <a class="btn btn-primary" href="#" role="button">Send back Heart</a>
                        </div>
                </div>
            {% endfor %}
    </div>
</section>
{% endblock %}

{% block javascripts %}

<script>

function markAsRead() {
    var slug = event.currentTarget.getAttribute('data-slug')
    var user_id = event.currentTarget.getAttribute('data-user')
    if ($(event.target).hasClass("btn") ){
        $.ajax({
            type:"POST",
            url:"/right_swipe/",
            headers:{
            "X-Requested-With": "XMLHttpRequest",
            "X-CSRFToken": getCookie("csrftoken"),
            },
            data:{
            "receiver":user_id,
            },
            success:(data) => { 
                triggerAlert(data["message"], data["status"]);
                $.ajax({
                    type:"POST",
                    url:"/inbox/notifications/mark-as-read/"+slug+"/",
                    headers:{
                    "X-Requested-With": "XMLHttpRequest",
                    "X-CSRFToken": getCookie("csrftoken"),
                    },
                    data:{
                    },
                    success:(data) => {
                        console.log("Marked as read")
                    },
                    error:(error) => {
                    console.log(error)
                    }
                })
            },
            error:(error) => {
                console.log(error)
            }
        })
    }else{
        $.ajax({
            type:"POST",
            url:"/inbox/notifications/mark-as-read/"+slug+"/",
            headers:{
            "X-Requested-With": "XMLHttpRequest",
            "X-CSRFToken": getCookie("csrftoken"),
            },
            data:{
            },
            success:(data) => {
                console.log("Marked as read")
                window.location="{% url 'profile_detail' 123 %}".replace(/123/,user_id.toString())
            },
            error:(error) => {
            console.log(error)
            }
        })
    }
}

function fetchdata(){
 $.ajax({
    type:"GET",
    url:"{% url 'matches' %}",
    headers:{
        "X-Requested-With": "XMLHttpRequest",
    },
    data:{
    },
    success:(data) => { 
        $(".notification-ui_dd-content").children().hide()
        $(".notification-ui_dd-content").html(data)
    },
    error:(error) => {
        console.log(error)
    }
 });
}

$(document).ready(function(){
    setInterval(fetchdata,1000);
});


</script>
{% endblock %}

templates/profile/list_notifications.html
{% for notification in notifications %}
            <div class="notification-list {% if notification.unread %} notification-list--unread{% endif %}"  data-slug="{{notification.slug}}" data-user="{{notification.actor.profile.id}}" onclick="markAsRead()">
                    <div class="notification-list_content">
                        <div class="notification-list_img">
                            <img src="{{notification.actor.profile.profile_picture.url}}" alt="user">
                        </div>
                        <div class="notification-list_detail">
                            <p class="text-dark"><b>{{notification.actor.profile.first_name}}</b> sent you a heart.</p>
                            <p class="text-muted">Send back a heart to start chatting now.</p>
                            <p class="text-muted"><small>{{notification.timestamp|timesince}} ago</small></p>
                        </div>
                    </div>
                    <div class="notification-list_feature-img">
                        <a class="btn btn-primary" href="#" role="button">Send back Heart</a>
                    </div>
            </div>
{% endfor %}

templates/profile/update_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block css %}

<link href=
'https://ajax.googleapis.com/ajax/libs/jqueryui/1.12.1/themes/ui-lightness/jquery-ui.css'
          rel='stylesheet'>


{% endblock %}


{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-5 mt-5">
            <div class="card">
                <div class="card-header">
                    <h1 class="display-6">Update Profile</h1>
                    <p class="lead">Edit your personal information here.</p>
                </div>
                <article class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            {{ form|crispy }}
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary btn-lg"> Update </button>
                        </div>
                    </form>
                </article>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}

<script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js"></script>

<script>

    $( "#id_date_of_birth" ).datepicker({
        changeMonth: true,
        changeYear: true,

        yearRange:'-90:+0'
      });
      
</script>


{% endblock %}

templates/profile/update_user_description.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block css %}

{% endblock %}


{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-5 mt-5">
            <div class="card">
                <div class="card-header">
                    <h1 class="display-6">Update your description</h1>
                    <p class="lead">Edit your personal description here.</p>
                </div>
                <article class="card-body">
                    <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div>
                            {{ form|crispy }}
                        </div>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary btn-lg"> Update </button>
                        </div>
                    </form>
                </article>
            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block javascripts %}



{% endblock %}

templates/profile/user_detail.html
{% extends 'base.html' %}
{% load custom_tags %}
{% load static %}


{% block css %}

<link rel="stylesheet" href="{% static 'css/user_profile.css' %}">

{% endblock %}

{% block content %}

<main class="profile mx-auto mt-5">
    <div class="profile-bg"></div>
    {% if object.user == request.user  %}
    <div class="d-flex justify-content-end align-items-center">
        <a href="{% url 'update_profile' user.profile.id %}" class="me-2"><i class="fa-solid fa-pen-to-square fs-4 text-dark"></i></a>
        <a href="{% url 'update_description' user.profile.description.id %}" class="btn btn-primary">Update Description</a>
    </div>
    <!-- <a href="{% url 'update_profile' user.profile.id %}" class="btn btn-primary">Update Description</a> -->
    {% endif %}
    <section class="container">
        <img src="{{object.profile_picture.url}}" class="profile-image" >
        <section class="profile-info">
        <h1 class="first-name">{{object.first_name}} {{object.last_name}}</h1>
        <h2>{{object.age}}</h2>
        <h2>{{object.zodiac}}</h2>
        <h2>{% calculate_distance request.user.id object.id %} KM Away</h2>
        <h2 class="bio mt-4">BIO</h2>
        <p>
            {{object.bio}}
        </p>
        <h2 class="bio">INTERESTS {% if object.user == request.user %}<a href="" class="text-end fw-light" data-bs-toggle="modal" data-bs-target="#exampleModal">Add more</a>{% endif %}</h2>
        <p>
            {% for interest in interests %}
                <span>{{interest.title}}</span> ,
            {% endfor %}
        </p>
        </section>
    </section>
    <section class="statistics">
        <p><strong>{{hearts_received.count}}</strong> Hearts Received</p>
        {% if object.user == request.user  %}
        <p><strong>{{hearts_sent.count}}</strong> Hearts Sent</p>
        {% endif %}
    </section>
</main>
{% if object.user != request.user  %}
<div class="container-fluid d-flex justify-content-center align-items-center tinder--buttons mt-5">
    <button id="nope"><a href="{{request.META.HTTP_REFERER}}"><i class="fa fa-remove"></i></a></button>
    <button id="love" data-id="{{object.id}}"><i class="fa fa-heart"></i></button>
</div>
{% endif %}



<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title fs-2" id="exampleModalLabel">Add your interest here</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <form action="{% url 'add_interest' %}" method="POST"> 
            {% csrf_token %}
            <input type="text" class="form-control" name="title" placeholder="Enter your interest">
            <button type="submit" class="btn btn-primary form-control mt-2">Add</button>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          
        </div>
      </div>
    </div>
  </div>



{% endblock %}

{% block javascripts %}

<script>

    $('#love').click(function(){
        var receiver = ($('#love').attr("data-id"))
        console.log(receiver)
        $.ajax({
            type:"POST",
            url:"/right_swipe/",
            headers:{
            "X-Requested-With": "XMLHttpRequest",
            "X-CSRFToken": getCookie("csrftoken"),
            },
            data:{
            "receiver":receiver
            },
            success:(data) => { 
                triggerAlert(data["message"], 'success');
            },
            error:(error) => {
                console.log(error)
            }
        })
    })

</script>

{% endblock %}